sudo: required
services:
  - docker
language: groovy
before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker run -d -p 27017:27017 mongo:latest
script:
  - docker build -t sdkman/sdkman-broadcast:2.0.4 .
  - docker run -d -p 9001:9001 --net=host sdkman/sdkman-broadcast:2.0.4
  - "./gradlew check"
after_success:
  - docker push sdkman/sdkman-broadcast:2.0.4
cache:
  directories:
  - "$HOME/.gradle"
# blacklist
branches:
  except:
    - RELEASE

